### ISSUE TITLE
not exactly an issue anymore

### ISSUE THREAD

**Issue by rsuchecki** [BioContainers/multi-package-containers#1313]
Just noticed that related repo have been archived before I got a chance to respond  https://github.com/galaxyproject/galaxy-lib/issues/156

========================================

Thank you both for your quick responses. 

@mvdbeek  I am pretty sure I've installed requests at some point, as well as Woosh. Now I tried again as per your instructions in a couple of fresh virtual environments for python 2 & 3. 

```
mulled-search -s bwa
Traceback (most recent call last):
  File "/tmp/ccc/.venv/bin/mulled-search", line 11, in <module>
    sys.exit(main())
  File "/tmp/ccc/.venv/lib/python3.6/site-packages/galaxy/tool_util/deps/mulled/mulled_search.py", line 321, in main
    conda_results[item] = conda.get_json(item)
  File "/tmp/ccc/.venv/lib/python3.6/site-packages/galaxy/tool_util/deps/mulled/mulled_search.py", line 127, in get_json
    use_exception_handler=True)
TypeError: 'NoneType' object is not callable
```
(Also tried on an mostly unused WSL ubuntu with the same result.)

@bgruening, I created the environment as per your instructions (added `-c bioconda`), but not quite there yet.  

```
(base) rad@radm:~/repos$ conda activate galaxy
(galaxy) rad@radm:~/repos$ which mulled-search 
/home/rad/miniconda3/envs/galaxy/bin/mulled-search
              
(galaxy) rad@radm:~/repos$ mulled-search -h
Traceback (most recent call last):
  File "/home/rad/miniconda3/envs/galaxy/bin/mulled-search", line 6, in <module>
    from galaxy.tool_util.deps.mulled.mulled_search import main
ModuleNotFoundError: No module named 'galaxy.tool_util'
(galaxy) rad@radm:~/repos$ mulled-search
Traceback (most recent call last):
  File "/home/rad/miniconda3/envs/galaxy/bin/mulled-search", line 6, in <module>
    from galaxy.tool_util.deps.mulled.mulled_search import main
ModuleNotFoundError: No module named 'galaxy.tool_util'
```

Then I remembered that channel order may play a part so tried `conda create -n galaxy2 galaxy-tool-util --override-channels -c conda-forge -c bioconda -c default`  and it works now :pray:

**Comment by bgruening** [comment]
@rsuchecki yes channel order is indeed very crucial. This one should also work: `conda create -n mulled galaxy-tool-util -c conda-forge -c bioconda`

Do you want to add this to the readme in this repo?

**Comment by mvdbeek** [comment]
> (Also tried on an mostly unused WSL ubuntu with the same result.)

I guess the conda package there is missing, I suppose that'd be `pip install conda`
