### ISSUE TITLE
Can't select packages to combine

### ISSUE THREAD

**Issue by sidorov-si** [BioContainers/multi-package-containers#1368]
Dear BioContainers team,

I tried to use the web service for combining packages (https://biocontainers.pro/#/multipackage) and couldn't select several packages present on BioContainers: `samtools`, `bedtools` and `pandas`.

When I type `samtools` in the Search box, it only shows me `bioconductor-rsamtools`. 

When searching for `bedtools`, it does show me some bedtools packages, but not all. For example, it doesn't show version `2.29.0`, although it exists on BioContainers (for example, `2.29.0--hc088bd4_3` here - https://quay.io/repository/biocontainers/samtools?tab=tags).

When searching for `pandas`, it only shows me `biopandas`, although `pandas` does exist: https://quay.io/repository/biocontainers/pandas?tab=tags

Could you please help me with this? Of course, I could just put the names and versions of the tools I need into `hash.tsv` by myself, but then I'm not sure how to obtain names of the corresponding containers.

Thank you,
     Slava

**Comment by bgruening** [comment]
@ypriverol can you please look at it?

**Comment by sidorov-si** [comment]
Meanwhile, I found where to take the name of the container if I can't have it from the web service: 

1) After my pull request is merged, I click "View details" besides the auto comment about the merge.

2) Click "Details" against "Travis CI - Pull Request Build Passed".

3) Click "The build" link in "The build passed, just like the previous build." sentence.

4) In the build progress output, find command `involucro` and its argument `REPO`. The latter gives the name of the container.

**Comment by pcantalupo** [comment]
Bumping this issue.  I'm having similar problems like @sidorov-si when searching for packages using the helper tool.    Also, when I search for `R` it returns irrelevant results.  Later I found that you need to search for `r-base`. How is a new user supposed to know that? Also when searching for `r-base` it returns only version 3.3.2.  
Thank you

**Comment by bgruening** [comment]
We have added some instructions how to search for containers to the main readme file, hope that helps.

You still need to know the package name as in every other package manager.
