### ISSUE TITLE
Way to know what packages are installed in a mulled container

### ISSUE THREAD

**Issue by sidorov-si** [BioContainers/multi-package-containers#1372]
Dear BioContainers team,

Is there a simple way to know what packages are installed in a mulled container? For example, if a have a container `mulled-v2-ac74a7f02cebcfcc07d8e8d1d750af9c83b4d45a:f480262c6feea34eb5a49c4fdfbb4986490fefbb-0`, how could I infer that it has `bowtie2=2.4.1`, `samtools=1.9` and `pigz=2.3.4`?

Thank you,
     Slava

**Comment by ryancey1** [comment]
Hi @sidorov-si, have you been able to find a way to do this?

**Comment by ggrimes** [comment]
You can run the docker image

```console
docker run --rm -it  quay.io/biocontainers/mulled-v2-ac74a7f02cebcfcc07d8e8d1d750af9c83b4d45a:f480262c6feea34eb5a49c4fdfbb4986490fefbb-0
```

And in the command prompt type

```console
/ # grep specs /usr/local/conda-meta/history
# update specs: ['pigz=2.3.4', 'samtools=1.9', 'bowtie2=2.4.1']
```

**Comment by ryancey1** [comment]
Thanks, @ggrimes!

**Comment by ryancey1** [comment]
Thanks, @ggrimes!

**Comment by bgruening** [comment]
I add some help on how to search also to the main readme file: mulled-hash changeo=1.2.0,igblast=1.17.1,wget=1.20.1
mulled-v2-7d8e418eb73acc6a80daea8e111c94cf19a4ecfd:e7f88c6f7da46a5407f261ca406c050d5bd12dea
