### ISSUE TITLE
Error while loading shared libraries: libbz2.so.1

### ISSUE THREAD

**Issue by rivera10** [BioContainers/multi-package-containers#1731]
Hello,

I got this error in one of the mulled containers
```
blastn: error while loading shared libraries: libbz2.so.1: cannot open shared object file: No such file or directory
```

Container ID:
```
mulled-v2-848eb9b6a829414c79e64bc96d43109620d1cfd9:869b2b6d573ee185276907ccda7237a29552a952-0
```

I thought on adding bzip2 to the list of software but the build process of the container already installs bzip2. Any suggestion on how to fix this?

Best,
Ramon

**Comment by bgruening** [comment]
Is it this one? https://github.com/BioContainers/multi-package-containers/pull/1727/files#diff-f6be21f33f5bb216e9a0baac781bc0d81da47c65d70a53701dfc6cac35c80966R100

I think you need to fix the blast conda package. It seems like it was not pinned to a specific libbz version. Or is there a newer blast version available?

**Comment by rivera10** [comment]
Yes that one. I will modify the blast. Hopefully that solves the issue

**Comment by rivera10** [comment]
[PR](https://github.com/BioContainers/multi-package-containers/pull/1732)
