### ISSUE TITLE
ncbi-datasets-cli 

### ISSUE THREAD

**Issue by jennahamlin** [BioContainers/multi-package-containers#2136]
Hello -

The ncbi-datasets-cli container does not download genome data from NCBI. I am able to launch the container and display the help menu. But when I attempt to use their example `datasets download genome taxon "bos taurus"`, I get this error: No assembly available. This error occurs when trying the 12.20.1 and 12.11.0 versions. I get a different error when I attempt to use the 11.25.1 version. The error is:
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x87ec9a]

goroutine 1 [running]:
main/datasets/datasets.baseRetryPolicy(...)
        src/datasets/datasets/root.go:182
main/datasets/datasets.DefaultRetryPolicy(0xa35290, 0xc0000280d0, 0x0, 0xa2dfc0, 0xc000316810, 0x0, 0x4ae360, 0x203000)
        src/datasets/datasets/root.go:152 +0x7a
github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc000145b90, 0xc0000b9c50, 0x0, 0x0, 0x0)
        external/com_github_hashicorp_go_retryablehttp/client.go:597 +0x1f1
github.com/hashicorp/go-retryablehttp.(*RoundTripper).RoundTrip(0xc00000e3f0, 0xc0001ed700, 0xc00000e3f0, 0x0, 0x0)
        external/com_github_hashicorp_go_retryablehttp/roundtripper.go:44 +0x85
net/http.send(0xc0001ed700, 0xa2c8c0, 0xc00000e3f0, 0x0, 0x0, 0x0, 0xc0000103b0, 0x8f2540, 0x1, 0x0)
        GOROOT/src/net/http/client.go:251 +0x454
net/http.(*Client).send(0xc0001fa240, 0xc0001ed700, 0x0, 0x0, 0x0, 0xc0000103b0, 0x0, 0x1, 0x0)
        GOROOT/src/net/http/client.go:175 +0xff
net/http.(*Client).do(0xc0001fa240, 0xc0001ed700, 0x0, 0x0, 0x0)
        GOROOT/src/net/http/client.go:717 +0x45f
net/http.(*Client).Do(...)
        GOROOT/src/net/http/client.go:585
main/openapi_client.(*APIClient).callAPI(0xc0000cd180, 0xc0001ed700, 0x0, 0xc000026f80, 0x34)
        src/generated/openapi_client/client.go:188 +0x4d
main/openapi_client.(*GenomeApiService).GenomeMetadataByPost(0xc0000cd188, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        src/generated/openapi_client/api_genome.go:1340 +0x46d
main/datasets/datasets.getAssemblyMetadataPage(0xc0000cd180, 0xc00014f980, 0x3e8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        src/datasets/datasets/SummaryGenomeAccession.go:61 +0x105
main/datasets/datasets.getAssemblyMetadataWithPost(0xc00014f980, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        src/datasets/datasets/SummaryGenomeAccession.go:100 +0x194
main/datasets/datasets.glob..func7(0xd06d80, 0xc0000b9890, 0x1, 0x1, 0x0, 0x0)
        src/datasets/datasets/DownloadGenomeTaxon.go:41 +0x10f
github.com/spf13/cobra.(*Command).execute(0xd06d80, 0xc0000b9870, 0x1, 0x1, 0xd06d80, 0xc0000b9870)
        external/com_github_spf13_cobra/command.go:842 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xd050a0, 0x4686c5, 0xc000000180, 0x200000003)
        external/com_github_spf13_cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        external/com_github_spf13_cobra/command.go:887
main/datasets/datasets.Execute()
        src/datasets/datasets/root.go:411 +0x31
main.main()
        src/cmd/datasets/main.go:10 +0x25

**Comment by mvdbeek** [comment]
We've been using the ca-certifcates images, which are unfortunately not getting picked up by default in go:
`[ -f /usr/local/ssl/cacert.pem ] && export SSL_CERT_FILE="/usr/local/ssl/cacert.pem"`
