### ISSUE TITLE
missing container

### ISSUE THREAD

**Issue by cmatKhan** [BioContainers/multi-package-containers#2248]
The container below seems to exists on [quay](https://quay.io/repository/biocontainers/mulled-v2-a1289c2d7470e63e3c3a9f6131984bbf7c28ad45?tab=tags&tag=2c0dd6dc388570cf3b02c569a856aa0d6e9dc84a-0), but not [galaxyproject.org/singularity](https://depot.galaxyproject.org/singularity/mulled-v2-a1289c2d7470e63e3c3a9f6131984bbf7c28ad45:2c0dd6dc388570cf3b02c569a856aa0d6e9dc84a-0). Is this expected?

mulled-v2-a1289c2d7470e63e3c3a9f6131984bbf7c28ad45:2c0dd6dc388570cf3b02c569a856aa0d6e9dc84a-0

which corresponds to this line in the `hash.tsv`:

```
python=3.9,matplotlib=3.5.1,pandas=1.3.5,r-sys=3.4,regex=2021.11.10,scipy=1.7.3
```

**Comment by bgruening** [comment]
It should not, this repo is taking care that both are in sync: https://github.com/BioContainers/singularity-build-bot/actions

**Comment by bgruening** [comment]
If you look here: https://quay.io/repository/biocontainers/mulled-v2-a1289c2d7470e63e3c3a9f6131984bbf7c28ad45?tab=tags

there are 3 containers and all 3 are also available as singularity.

**Comment by bgruening** [comment]
Hope that helps.
