### ISSUE TITLE
Build container for a conda-forge package?

### ISSUE THREAD

**Issue by sralchemab** [BioContainers/multi-package-containers#2271]
Hi there,

I would like to create a single-package container for a package from conda-forge. Will updating the `hash.tsv` file with this package work? If not, how should I proceed in this situation?

The package is:

levenshtein=0.20.1

Thank you very much in advance.

**Comment by bgruening** [comment]
Yes this will work :-)

**Comment by sralchemab** [comment]
Thanks, bjorn! And will the container get the name of the package, as in `quay.io/biocontainers/levenshtein:0.20.1` or will it be something like `mulled-...`?

**Comment by bgruening** [comment]
The same name :-)

**Comment by sralchemab** [comment]
Amazing! Thanks!
