### ISSUE TITLE
Create a multi-package-container for modbam2bed

### ISSUE THREAD

**Issue by ekushele** [BioContainers/multi-package-containers#2389]
Hi,

I'm trying to generage a container for [modbam2be](https://github.com/epi2me-labs/modbam2bed).

I've tried the helper service, but it couldn't find either modbam2bed package or epi2melabs channel.

What can I do?

Thank you!

**Comment by bgruening** [comment]
Hi, at first you need to create a bioconda package: https://bioconda.github.io/contributor/index.html

If this is merged you will get a container automatically :)

**Comment by ekushele** [comment]
Thank you!
In fact, the package is avaliable from a conda package, and can be installed wuth the command: 
`mamba create -n modbam2bed -c bioconda -c conda-forge -c epi2melabs modbam2bed`

(From: [here](https://github.com/epi2me-labs/modbam2bed#installation)
Is it enough?

**Comment by bgruening** [comment]
Yes, in this case please follow https://github.com/BioContainers/multi-package-containers#building-multiple-package-containers

**Comment by ekushele** [comment]
I couldn't find "modbam2bed" on the helper, that's why I opened this issue

**Comment by bgruening** [comment]
What do you mean with "on the helper"? You need to add "modbam2bed" to this repo.

**Comment by ekushele** [comment]
I thought I only need to search for the package in the [helper service](https://biocontainers.pro/multipackage) and use the "mulled" tool to make a container for it

**Comment by ekushele** [comment]
I don't understand what exactly I need to do..
Will you please be able to explain to me?

**Comment by ekushele** [comment]
@bgruening I tried to add modbam2bed to the hash.tsv table but maybe I did something wrong, because the test failed.

I would appreciate it if you could help me
