### ISSUE TITLE
Rebuild container in hash.tsv

### ISSUE THREAD

**Issue by prototaxites** [BioContainers/multi-package-containers#2650]
Hi all,

Not quite sure how to do this, but I'd like to rebuild the container `cat=4.6,diamond=2.0.6` listed on line 137 of hash.tsv.

It seems this image was built before a bug with exposing resolv.conf in Singularity images was fixed (https://github.com/bioconda/bioconda-recipes/issues/11583), which means that the image is unable to get network access (at least on my system).

What do I need to include in a PR to rebuild the container with an up-to-date base image?

**Comment by bgruening** [comment]
You can add a build number of 1 into the line.
