### ISSUE TITLE
Readable names are needed

### ISSUE THREAD

**Issue by rhpvorderman** [BioContainers/multi-package-containers#834]
Current container names are indiscernable from eachother.
```
mulled-v2-05fd88b9ac812a9149da2f2d881d62f01cc49835:f0f80d4cb5631deb3715817144cb290221be9d1c-0
mulled-v2-0df1816856a9b13d24526c54b9a0cfb0caa5b6c5:1b03ef4ed69b011d06a426e4b5a1a3cc28cb81b0-0
```
- What is in these containers?
- What is the most recent version of a certain combination?

The names are so unique, that in practice they are **all the same**! They all look like a bunch of hexadecimals to me and therefore have no uniqueness or discernability whatsoever.

Can we move to an actual informative naming scheme?
For example container `mulled-v2-9ce0e23bf798aa283902800c4cd106adf15090b2:38c4658d41b94a7b6f5d06712831441c5b522b09-0` contains
```
py-graphviz=0.4.10,graphviz=2.38.0
```
Why not call this `py-graphviz+graphviz:0.4.10+2.38.0`

It is readable, it is clear what versions are used, and it is discernable from other containers. Yes, it will get a bit long when there are more packages. But given the already quite long length of the current combinations this is not really a big problem.

**Comment by bgruening** [comment]
> Why not call this py-graphviz+graphviz:0.4.10+2.38.0

Because these names can become very long, it needs to be normalized, `+` can be in version strings etc ... the short story it's super complicated.

> They all look like a bunch of hexadecimals to me and therefore have no uniqueness or discernability whatsoever.

You are not supposed to look at them ;) You have a hash function which you give a bunch of names and you get back the container. It meant for automatic systems like Galaxy, Snakemake, Nextflow etc ...

**Comment by rhpvorderman** [comment]
Hmm, I understand. Allthough it is quite inconvenient. Each docker container already has a unique hash referring to it. The name is to make it readable for humans. If you replace it with a hash, that is not really helpful.

I do understand the implementation concerns. Auto-generating human-readable names will be different given that not everyone keeps to semantic versioning etc.

My practical problem is as follows: I write a lot of WDL for the [BioWDL project](www.github.com/biowdl). And there I have to add default containers manually, and I can't see what they do.

Could you link to the hash function that is used to generate the names? Maybe we can leverage that to put readable names in the wdl itself. That would work around the problem.

Thanks!

**Comment by bgruening** [comment]
> Hmm, I understand. Although it is quite inconvenient. Each docker container already has a unique hash referring to it. The name is to make it readable for humans. If you replace it with a hash, that is not really helpful.

You still need to find the container and pull it.

> My practical problem is as follows: I write a lot of WDL for the BioWDL project. And there I have to add default containers manually, and I can't see what they do.

You could use CWl, cwltool has already support for this via galaxy-lib.

> Could you link to the hash function that is used to generate the names? Maybe we can leverage that to put readable names in the wdl itself. That would work around the problem.

V1 and V2 ... https://github.com/galaxyproject/galaxy-lib/blob/07b969488ebb210d9a2c039273cbec634833e981/galaxy/tools/deps/mulled/util.py#L131 also there is a JS-based implementation somewhere here: https://github.com/BioContainers/multi-package-containers/tree/gh-pages

**Comment by rhpvorderman** [comment]
> You still need to find the container and pull it.

Yes exactly. This naming scheme makes that very difficult. It is only possible with external tools.

Thanks a lot @bgruening for pointing me to the tools necessary to automate this in WDL. 

Maybe this issue can be kept open for future reference? With a wontfix label? It is very hard to fix in a good way. But maybe some future genius is able to crack this nut, while also making combinations do the auto-update via bioconda-bot.

**Comment by bgruening** [comment]
> Yes exactly. This naming scheme makes that very difficult. It is only possible with external tools.

Btw. we do offer these external command line tools.

> Maybe this issue can be kept open for future reference? With a wontfix label? It is very hard to fix in a good way. But maybe some future genius is able to crack this nut, while also making combinations do the auto-update via bioconda-bot.

I will close it, google will still find it and people searching in the issues will also find it. Ok?

**Comment by rhpvorderman** [comment]
Thanks for being so helpful!
