### ISSUE TITLE
Multi-packages container updates, extended base image

### ISSUE THREAD

**Issue by mvdbeek** [BioContainers/multi-package-containers#940]
Hi everyone,

We’ve recently tried to containerize around 2000 high quality Galaxy tools. All of these tools contain test cases (2800 in total) that we can run programmatically, and before accepting a new tool or upgrading a tool these tests are run. Previously these tests ran on travis-ci using Conda to satisfy any dependency. Running containerized tests revealed two very common classes of errors which I think we should address:

1) We don’t respect the extended-base requirement annotated in many bioconda recipes, which leads to broken multi-package-containers (bioconda sets the destination image when building biocontainers). I’ve fixed this in galaxy-tool-util by checking if any of the specified recipes requires the extended base container. A new version of planemo will roll this out. But I think we also need to indicate that a container has been built with the extended base somewhere. We could record whether the minimal base image or the extended base image (or other images we may need in the future, think GPU etc...) @bgruening proposed to prefix the combinations with container:extended;<package1>,<package2> etc.
One issue here is that we’ll only know that a container needs the extended base after running the check in galaxy-tool-util, so I’m not sure what could be done about the helper service (https://biocontainers.pro/#/multipackage).

2) We don’t update multi-containers when new package builds are published to Conda. New builds are frequently published because of missing dependencies, and so multi-package-containers are frequently broken despite the problem being fixed upstream. I think it would be feasible to scan for new builds and increment the multi-container build number (possibly also deleting the earlier build should we run into space problems). I think this is the biggest time-sink when switching a large code-base from Conda to containers at this point. Relatedly I think we should record the build numbers of a build somewhere, so that we know with which build numbers we are dealing with.
One suggestion here would be to include the Conda build numbers, so we would have `container:extended;<package1>--<build2>,<package2>--<build10>`.
Again it would be great to get some suggestions for how to manage this.
If adding new versions would be restrictive in terms of size we could prune everything but the newest version. I think getting working and up to date containers should be higher priority than maintaining potentially broken containers (but I can see that this might be controversial).
Another more limited option is to prefix the build number, so we’d have  `build:2;container:extended;<package1>,<package2>` etc.
That also gives us a nice handle on manually triggering a rebuild. Detailed build info could still be parsed out manually or on a CI system from /usr/local/conda-meta.

**Comment by jmchilton** [comment]
> (possibly also deleting the earlier build should we run into space problems).

We shouldn't be doing that IMO - we might break things.

I think rather than scanning and auto-upgrading the multi-package containers - we should just have a way to quickly auto-rebuild and publish a new container when problems are encountered. I think there will be a lot fewer of these problems once the tools themselves are tested in containers before they're merged.

**Comment by mvdbeek** [comment]
This is too much work, mostly because identifying problems is not so easy. Then finding out it's already fixed is ... not very fun.

**Comment by mvdbeek** [comment]
Maybe we can first try doing the auto-updates and then see if it really is a problem ? Maybe it isn't that bad, and as you said it should become less common over time.

**Comment by jmchilton** [comment]
If the IUC tool is published and has been tested then we know the container is solid - so presumably we publish the container a day later - it will still be solid. If we auto-create a container for some random package upgrade 6 months later - a lot more things are likely to have been broken and we will have no testing of the new combination of packages. I think we should at least focus on getting things tested before they're published and then see if this is needed - because it scares me.

**Comment by mvdbeek** [comment]
> so presumably we publish the container a day later - it will still be solid. 

We can't know that, but my gut feeling is that newer builds are less likely to be broken than old builds. Maybe space won't be an issue ? If this service becomes more successful we'd be running into space issues as well, so l'd say let's see how it goes ?

> I think we should at least focus on getting things tested before they're published and then see if this is needed - because it scares me.

Sure, that's what I'm doing and that lead me to the conclusion that we absolutely need auto-updates if we want the community to adopt containers.

**Comment by mvdbeek** [comment]
On the other hand manual bumps are certainly easier to implement and would already help. @bgruening had the same concern, and it is a similar procedure to get new build in bioconda.

**Comment by bgruening** [comment]
@mvdbeek you know my opinion already :)

Let's focus on `container:extended;<package1>--<build2>,<package2>--<build10>` and `build:2;container:extended;<package1>,<package2>` and see how far we get?

Btw. thanks for pulling this together!

**Comment by mvdbeek** [comment]
So I was sitting there, getting ready to code and then I see @jmchilton already implemented the build number bumping logic 😆. We just need to add a second column with the build number in the tsv files.

**Comment by jmchilton** [comment]
🙈

**Comment by bgruening** [comment]
I think this is now working since a few years :) Thanks everyone.
